### ISSUE TITLE
Create new sidebar structure for Build

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#100]
The build section should have the following sidebar structure:

```
├── Introduction
├── Build Circuits with Qiskit
│   ├── Circuit Library
│   └── Circuit Construction
│   ├── Circuit Visualisation
│   ├── Classical feedforward and control flow
│   └── Order of Qubits in Qiskit
│
├── Build Operators with Qiskit
│   ├── Specifying Observables in the Pauli basis (to be written)
│   ├── Operators module Overview
│   └── Synthesizing circuits from operators (to be written)
│
├── Other Circuit Building tools
    ├── Tune Pulse Waveforms
    └── OpenQASM
        ├── What is OpenQASM
        └──  OpenQASM2 and Qiskit
        ├── OpenQASM3 and Qiskit
        ├── OpenQASM3 Feature table
        └── OpenQASM spec
```

Before completing this work, the following PRs should be merged (otherwise theres not enough content to make the folder structure not look weird):
- https://github.com/Qiskit/documentation/pull/156
- https://github.com/Qiskit/documentation/pull/217

also t[his page](https://docs.quantum-computing.ibm.com/build/operators_overview) should be re-titled "Operators module Overview"

**Comment by abbycross** [comment]
Question @javabster -- for [this page](https://docs.quantum-computing.ibm.com/build), when we change the title in the toc to Introduction, we should also change the title on the page itself so that they match. Do you prefer just "Introduction" as the title, or "Introduction: Build circuits with Qiskit" or something like that? I'm fine either way.
