### ISSUE TITLE
API Docs font and color suggestions

### ISSUE THREAD

**Issue by levbishop** [Qiskit/documentation#1131]
### Feedback

For example https://docs.quantum.ibm.com/api/qiskit/qiskit.primitives.StatevectorSampler
<img width="1654" alt="image" src="https://github.com/Qiskit/documentation/assets/18673315/1c002757-7d64-4d9f-b28e-d81221b265eb">

Problems making this hard to read:
1. So much white space, such tiny text
2. Serif font
3. Low contrast darkish gray on slightly less darkish gray (especially for comments)
4. proportional font for code(!)

Compare to eg tensorflow (which isn't anything special just the first thing came to mind)
<img width="1652" alt="image" src="https://github.com/Qiskit/documentation/assets/18673315/8fb7b020-8b78-452d-ba89-a52e22ff05b7">

1. Less white space, larger text
2. Sans serif
3. High contrast. Comments are magenta on light gray
4. Monospace code

**Comment by Eric-Arellano** [comment]
The font is not loading correctly for you, which is something we've been trying to figure because it only sometimes happens. For example, I cannot reproduce. Although some of the suggestions apply regardless of the font - like coloring code comments.

I'll message you for help with debugging the font not loading.

**Comment by Eric-Arellano** [comment]
Thanks for the comments, @levbishop! We've rolled out a few improvements since your issue:

1. the font loading bug is fixed
2. font-size increased from 12px to 14px
3. comments have more contrast than before

Your feedback was really helpful! 

<img width="750" alt="Screenshot 2024-08-08 at 10 43 42 AM" src="https://github.com/user-attachments/assets/60c87b1a-00df-4d94-96c5-08ed4d4295af">
