### ISSUE TITLE
Show more sample output with primitives

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#1143]
### Feedback

It's useful to see the output of primitives code to understand how they behave. We don't show this in https://docs.quantum.ibm.com/run/primitives-get-started, https://docs.quantum.ibm.com/run/primitives, https://docs.quantum.ibm.com/run/primitives-examples. We only have print statements that aren't executed. 

### Other comments

This could be somewhat addressed by rewriting the files to Jupyter notebooks that show the output: https://github.com/Qiskit/documentation/issues/169.

**Comment by beckykd** [comment]
the difficulty with converting these to notebooks is that they show V1 vs V2 and we haven't figured out how to nicely do that in notebooks.  But I can add output

**Comment by abbycross** [comment]
Jumping in, since I just went through the process of converting an mdx file with tabs in it, to ipynb. 
 
For the uninitiated, tab syntax is like this:

`<Tabs>`
 ` <TabItem value="value1" label="label1">`
`  </TabItem>`
  `<TabItem value="value2" label="label2">`
`  </TabItem>`
`</Tabs>`

If there were a way to include two types of code cells within each `TabItem`, there would be no problem. We generally need at least one markdown cell and at least one code cell for each tab.

Since (so far) it seems we can't do that, both the markdown and the code must be enclosed within one markdown cell, which means the code cannot get checked by the linter.

It also renders difficult the ability to display the output of the code, since it has to be manually placed, rather than simply running the code and including the output from that.

Hoping some other, better solutions will bubble up :)

**Comment by beckykd** [comment]
> Jumping in, since I just went through the process of converting an mdx file with tabs in it, to ipynb.
> 
> For the uninitiated, tab syntax is like this:
> 
> `<Tabs>` ` <TabItem value="value1" label="label1">` ` </TabItem>` `<TabItem value="value2" label="label2">` ` </TabItem>` `</Tabs>`
> 
> If there were a way to include two types of code cells within each `TabItem`, there would be no problem. We generally need at least one markdown cell and at least one code cell for each tab.
> 
> Since (so far) it seems we can't do that, both the markdown and the code must be enclosed within one markdown cell, which means the code cannot get checked by the linter.
> 
> It also renders difficult the ability to display the output of the code, since it has to be manually placed, rather than simply running the code and including the output from that.
> 
> Hoping some other, better solutions will bubble up :)

This is why I haven't converted any. :)

**Comment by beckykd** [comment]
run/primitives.mdx doesn't have any print statements.

**Comment by beckykd** [comment]
> You can actually wrap notebook cells in tab blocks. Just end a markdown cell with `<Tabs><TabItem value="value1" label="label1">` (plus any markdown content you want in the tab), then add your code cell, then start the next markdown cell with `</TabItem><TabItem value="value2" label="label2">` etc.
> 
> It's not perfect (from an editing standpoint) but worked OK for me in [`docs/build-new/plot-quantum-states.ipynb`](https://github.com/Qiskit/documentation/blob/main/docs/build-new/plot-quantum-states.ipynb).

I don't see tabs in that notebook.

**Comment by frankharkins** [comment]
Yes sorry the tabs don't render in the GitHub notebook viewer but they work correctly on the website, see this preview for an example: https://qiskit-docs-preview-pr-1160.1799mxdls7qz.us-south.codeengine.appdomain.cloud/verify/plot-quantum-states

**Comment by beckykd** [comment]
> Yes sorry the tabs don't render in the GitHub notebook viewer but they work correctly on the website, see this preview for an example: https://qiskit-docs-preview-pr-1160.1799mxdls7qz.us-south.codeengine.appdomain.cloud/verify/plot-quantum-states

Oh great!!
