### ISSUE TITLE
Add tutorial on error mitigation with Qiskit Runtime Estimator

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#1168]
[ CURRENTLY UNDER PRODUCT REVIEW IN QTE REPO]

This tutorial is based on[ a summit demo](https://learning.quantum.ibm.com/tutorial/scale-quantum-computational-workflows) but uses Estimator instead of Sampler. It is a new notebook created by Saki and Pedro on Nate's team, please work with them on this issue.

- [ ] move [source file](https://github.com/IBM-Quantum-Technical-Enablement/quantum-enablement/tree/main/docs/notebooks/scaling-estimator) into this repo
- [ ] review and refactor if needed. currently only works well with estimator v1 but not v2. Address any feedback from product review

**Comment by javabster** [comment]
update: this issue is now also covering the sampler scaling notebook too:

This tutorial is based on a [summit demo ](https://learning.quantum.ibm.com/tutorial/scale-quantum-computational-workflows)and was refactored by Ritajit on Nate's team, please work with him on this issue.

- [ ]  move [source file](https://github.com/IBM-Quantum-Technical-Enablement/quantum-enablement/tree/main/docs/notebooks/scaling-sampler) into this repo
- [ ]  review and refactor if needed. Address any feedback from product review in QTE repo

**Comment by kevinsung** [comment]
The original notebooks were designed for a Summit presentation. The needs of a tutorial on the learning platform are a bit different, and I'd like to make a few changes for pedagogical reasons:

- Replace usage of MBL circuit and operators with [EfficientSU2](https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.library.EfficientSU2) and random operators. Using a circuit included in Qiskit's circuit library allows the tutorial to focus on the learning goal, which is to teach how to use error mitigation with Qiskit Runtime.
- Use different simulation strategies for the two notebooks, to reduce duplicated content:
  - Keep mirror circuits for estimator tutorial.
  - Use Cliffordization for sampler tutorial.
- For the sampler tutorial, omit computation of expectation values, and just treat the bitstring distribution as the outcome. This avoids potential confusion about the purposes of each primitive, since the Estimator is recommended for expectation values.
