### ISSUE TITLE
Wildcard: allow running our notebooks with simulators?

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#1174]
We are using more hardware rather than simulators in our notebooks. This is meant to help users by showing real-world workflows, where the emphasis is running on actual hardware rather than simulators. 

We don't want to complicate the notebooks by showing both simulators and hardware.

However, that poses a challenge for our docs writing pipeline:

1. We cannot easily test the jobs in every CI run (https://github.com/Qiskit/documentation/issues/1173)
2. It is harder for us to get sample output for the notebooks to show to the user

This issue is to explore the idea of allowing us to dynamically rewrite our notebooks to use simulators rather than hardware when using our tool `nb-tester`. It would, for example, rewrite the backend to use `FakeManilaV2`. We'd need to figure out the rewriting of the code, along with reckoning with simulators not working when the qubit count is too high.

**Comment by frankharkins** [comment]
@beckykd had the idea of overwriting the `least_busy` function to always return `FakeManilaV2`. I'm trying it out now with a patched fork and it seems to work pretty well bar a few quirks we can probably iron out.

1. `docs/start/hello-world.ipynb` fails in the final cell with

   ```pytb
   AttributeError: 'DataBin' object has no attribute 'ensemble_standard_error'
   ```
   Because the fake backend doesn't set that attribute. We could just avoid using this attribute as they're only used for error bars in the plot.
2. `tutorials/submitting-transpiled-circuits/notebook.ipynb` fails when using `Batch`. It's possible this notebook is just broken anyway as there were some changes to batch mode recently.

   ```pytb
   AttributeError: 'QiskitRuntimeLocalService' object has no attribute 'backend'
   ```
3. This doesn't work for `tutorials/build-repitition-codes/notebook.ipynb` and `tutorials/build-repitition-codes/notebook.ipynb` as they use `qiskit-ibm-provider`. We probably want to switch them to runtime anyway.

**Comment by Eric-Arellano** [comment]
@frankharkins it may be desirable for us to always try to have the notebooks work without issue with local simulators, and even communicate to users that they can swap out `.least_busy()` with `FakeManilaV2`. That allows us to have hardware-first docs, but that are still accessible. So, when we have issues like the above, that means we should update the docs to work with simulators. The one fundamental barrier I see is if we need to use utility-scale # of qubits?

Re: implementation, we could maybe have `nb-tester` add a code block to "monkeypatch" Runtime `.least_busy()` for us, but hide it from users. Python is quite flexible like that:

```
>>> type(str("123"))
<class 'str'>

>>> str = int
>>> type(str("123"))
<class 'int'>
```
