### ISSUE TITLE
release notes, previous to 0.20, have unexpected links to API 

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/documentation#1178]
**Describe the bug**

The website https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/release-notes includes some funky link. While they work as expected, it seems that they do not look as expecting:

**Steps to reproduce**

 * Go to https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/release-notes
 * Ctrl+F and search for ``>`__``
 * See 116 instances of Sphinx syntax showing up after rendering

![screencapture-docs-quantum-ibm-api-qiskit-ibm-runtime-release-notes-2024-04-11-12_59_00-2](https://github.com/UC-Advanced-Research-Computing/UC-Quantum-tools/assets/766693/1522cf7a-8b28-4b3b-b03d-791e5250e091)

**Comment by arnaucasau** [comment]
@Eric-Arellano, I think it might be just a problem with the Box artifact being out of date. The problem should have been fixed by https://github.com/Qiskit/qiskit-ibm-runtime/pull/1553 which was incorporated into the `stable/0.22` branch after the [release](https://github.com/Qiskit/qiskit-ibm-runtime/commits/stable/0.22/). Tomorrow, I can look into it more closely, but maybe this can help

**Comment by kt474** [comment]
You're right, sorry I forgot that this was already fixed - we released qiskit-ibm-runtime 0.23.0 today so updating those docs should fix this issue

**Comment by arnaucasau** [comment]
Closing the issue because the docs for v0.23.0 have been generated together with the fix for the release notes in #1182. Thank you @1ucian0 for opening the issue!
