### ISSUE TITLE
ToC with duplicated entries

### ISSUE THREAD

**Issue by arnaucasau** [Qiskit/documentation#1196]
There are pages with duplicated headers that create duplicated entries in the ToC. An example can be found in this [page](https://docs.quantum.ibm.com/api/qiskit/0.44/qasm3#dump):

![Captura desde 2024-04-18 16-29-27](https://github.com/Qiskit/documentation/assets/47946624/d5ac4d80-352f-426d-8928-d5b4f72bd36c)

In that case, we have functions at the beginning of the page, and afterward, an inlined class that contains two methods with the same name.

**Comment by Eric-Arellano** [comment]
Fixed by @arnaucasau's header hierarchy improvement 🚀 toc of https://docs.quantum.ibm.com/api/qiskit/0.44/qasm3#dump

<img width="272" alt="Screenshot 2024-05-10 at 10 29 36 AM" src="https://github.com/Qiskit/documentation/assets/14852634/fd7e3948-ad07-4628-8896-43083be6d3e4">

There still is a top-level `dump` function vs `Exporter.dump`, but now the header is lower for the method so it's not confusing

<img width="705" alt="Screenshot 2024-05-10 at 10 29 58 AM" src="https://github.com/Qiskit/documentation/assets/14852634/b6c3dbff-91f1-4726-9d46-aa353aa636d5">
