### ISSUE TITLE
Header generation broken for specific dunder method

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#1275]
https://github.com/Qiskit/documentation/blob/c387562e8ca3dac26a653cb96773022bd78410bf/docs/api/qiskit/dev/circuit.mdx?plain=1#L652-L654

This should be `__array__`

**Comment by arnaucasau** [comment]
The problem with this method is that Sphinx generated the `id` without the double underscore at the beginning, and our script uses that `id` to set the header.

```html
<dt class="sig sig-object py" id="array__">
```

In this case, I think it should be fixed in the qiskit repo, by adding the module's name in front of the method similar to how the rest of the methods of that page are defined. This method is special-cased by setting the module to `None` [here](https://github.com/Qiskit/qiskit/blob/fe275a0f15132073c6b5afb0c4be8bcc351479cb/qiskit/circuit/__init__.py#L835), so one solution is to remove that line and line 843.

The change will also fix a cross-reference to `params` (line 838) that is currently broken. This will be the output of Sphinx after the fix.

![Captura desde 2024-05-09 22-54-17](https://github.com/Qiskit/documentation/assets/47946624/35efa457-4c09-4f82-8c77-1e00494ca252)

And this will be the new id that will help set the correct header:
```html
<dt class="sig sig-object py" id="qiskit.circuit.array">
```

What do you think? I can open a PR there if you think it's a good solution. I've been trying different things like escaping the underscores, but it didn't work. 

Another solution could be to change our script to use the signature for all headers, but not sure if that's feasible always (I can test it) and it will increase the complexity of the script even more.

**Comment by Eric-Arellano** [comment]
Great investigation, @arnaucasau! The output would be wrong to call it `qiskit.circuit.__array__` because we're talking about a generic under method `__array__` that you define on any class. We could do `Gate.__array__`, but better is simply `__array__`

What happens if you use `.. py:function::` rather than `py:method`?

Re the broken cross-reference, can that be fixed by using the fully qualified path to `Instruction.params`?

**Comment by arnaucasau** [comment]
> What happens if you use `.. py:function::` rather than `py:method`?

Nothing changes in that case. It sets the `dl` class to `function`, but the `id` is the same as before :thinking: 
```html
<dl class="py function">
<dt class="sig sig-object py" id="array__">
```

> Re the broken cross-reference, can that be fixed by using the fully qualified path

Yes, we can fix params by using `:attr:~qiskit.circuit.Instruction.params` :+1:

**Comment by Eric-Arellano** [comment]
> Nothing changes in that case. It sets the dl class to function, but the id is the same as before 🤔

Hm, what about setting the module to `builtins` or `__builtins__`? If that doesn't work, can you get it to render as `Gate.__array__`?
