### ISSUE TITLE
document primitive `mode` arg

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#1542]
followup from https://github.com/Qiskit/documentation/issues/1486#issuecomment-2160933818

```
with Batch(backend=backend):
    sampler = SamplerV2(mode=batch)
```

**Comment by beckykd** [comment]
Moving this to P0 because it's already been released.   I got this message today: 

The 'backend' keyword arguments are deprecated as of qiskit-ibm-runtime 0.24.0 and will be removed no sooner than 3 months after the release date. Please use the 'mode' parameter instead.
  sampler = Sampler(backend=backend)
