### ISSUE TITLE
[epic] Qiskit Functions: decide if we want to test any of the notebooks

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#1951]
We skip all of the notebooks by setting `notebooks_exclude` in `notebook-testing.toml`. Should we test any of these?

Update: sync with David, Iskander, and Sanket about what they think is reasonable. We should also consider https://github.com/Qiskit/documentation/issues/1173 or adding Pylint.

**Comment by frankharkins** [comment]
Discussed in meeting: We could try a static analysis tool like pylint to detect things like undefined variables and typos in module names. Related to #1806.

**Comment by frankharkins** [comment]
I spoke to @johannesgreiner today about this. Most functions take a backend name (str) rather than a backend object, which means our `least_busy` patch won't work. Here's what we're thinking:

1. To start, we'll try testing the functions notebooks in the fortnightly cron job. We may need a bit of extra code to find/replace standardized strings like `<YOUR_API_TOKEN>` and `<YOUR_IQP_GROUP>`, and some notebooks will need tweaking to run from start to finish (see #2239 for full issue).

2. We can test functions that don't post-process results using the IBM test backends. This will submit jobs that should run very quickly and return nonsense results. We'll need to add some more patching code, but it'll hopefully mean we can test these notebooks on PR, which would be great (full issue: #2240)

**Comment by frankharkins** [comment]
Closed in #2463
