### ISSUE TITLE
"No cloud instance" case not reported by QiskitRuntimeService "instances". Channel setting not taken into account

### ISSUE THREAD

**Issue by acastellane** [Qiskit/documentation#2153]
### URL to the relevant documentation

https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.QiskitRuntimeService#instances

### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [x] other

### Describe the fix.

In my settings, I only have IQP instances.
With the following I'm expected to see if I have any cloud instances (which I don't have) 
```
service = QiskitRuntimeService(channel='ibm_cloud')
service.instances()
```
it will report the iqp instances information and doesn't say "you don't have any cloud instances, I'll try to report any other instances"
This might be misleading for a new user.

Taking into account the user selected channel could improve the reports.

**Comment by abbycross** [comment]
@acastellane when I tried to replicate this, I couldn't get the output to list my ibm_quantum instances when I had ibm_cloud listed as a channel. Here's what I saw - is it different from what you see?:

![Image](https://github.com/user-attachments/assets/e5608e69-75a8-4b64-b411-f925d6cdad30)

**Comment by acastellane** [comment]
Hi, 
I get the same now, after I saved the cloud lite account. When I had only IQP instances saved, I got the same answer for both cases (eg IQP instances list)
Hope this helps.

**Comment by raulotaolea** [comment]
The method `instances` of `QiskitRuntimeService` [always returns an empty array](https://github.com/Qiskit/qiskit-ibm-runtime/blob/5a4d9dde7b5ddc0ad6d117516aa73a41f2a22d9e/qiskit_ibm_runtime/qiskit_runtime_service.py#L1161) for a channel different to `ibm_quantum`. So not sure what happened in this case. In addition, in order to get any information from a channel, you need a valid token for each channel. If you didn't establish one for `ibm_cloud` channel, the `QiskitRuntimeService` would not have been able to access to your IBM Cloud account. In any case, I don't think this is a doc issue, because the description explicitly says:

```
Return the IBM Quantum instances list currently in use for the session.
```

I doesn't say that you can get the instances from IBM Cloud.

**Comment by raulotaolea** [comment]
I think I found the error:

<img src="https://github.com/user-attachments/assets/17490af2-a31a-4457-96ec-5259adb64661" width="50%" />

It seems that when you save your IBM Quantum account without a name, it becomes your default account. So whenever you use `QiskitRuntimeService` without providing a name, it takes your default one, that in this case is your IBM Quantum account. The bug is that when you provide a channel but not a name in the constructor of `QiskitRuntimeService`, it looks for your default account without taking into account that it belongs to a different channel. So it uses it as your account. This is why it returns your IQP instances instead of the IBM Cloud.

That said, if we fix this bug, it will return an empty array. In IBM Cloud channel you have to explicitly provide the instance you want to connect to, so it is not feasible to return all the instances. This is the reason why it returns an empty array.

Feel free to open an issue in the [qiskit-ibm-runtime repo](https://github.com/Qiskit/qiskit-ibm-runtime/issues) using this description.

**Comment by acastellane** [comment]
If I delete the cloud account, and request
```
service = QiskitRuntimeService(channel='ibm_cloud')
service.instances()
```
I get something that makes sense.

```
File ~\py_qiskit_env\lib\site-packages\qiskit_ibm_runtime\accounts\management.py:197, in AccountManager.get(cls, filename, name, channel)
    194     if account_name in all_config:
    195         return Account.from_saved_format(all_config[account_name])
--> 197 raise AccountNotFoundError("Unable to find account.")

AccountNotFoundError: 'Unable to find account.'
```

**Comment by abbycross** [comment]
Closing this issue as it won't require changes to the docs - if this changes, feel free to re-open.
