### ISSUE TITLE
Typo in course Quantum Business Foundations

### ISSUE THREAD

**Issue by varun3392** [Qiskit/documentation#2170]
### URL to the relevant documentation

https://learning.quantum.ibm.com/course/quantum-business-foundations/quantum-computing-fundamentals

In the section **How quantum computing is different from classical**, at the end of the first paragraph, the documentation states _At any point in the computation, a classical computer’s state is entirely determined by the states of all its bits, so that a computer with n bits can exist in one of **2n** possible states_

### Select all that apply

- [x] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

It should say _At any point in the computation, a classical computer’s state is entirely determined by the states of all its bits, so that a computer with n bits can exist in one of **2^n** possible states_

**Comment by abbycross** [comment]
Hello! I will pass this along to the IBM Quantum Learning team. Thanks for reporting!

**Comment by christopherporter1** [comment]
Hi All. This is fixed. But it turns out it wasn't a typo. Directus is failing to parse html tags like <sub> and <\sub> and actually undoes corrections to the syntax! I fixed it by using latex notation. But this likely indicates a TON of other such instances. Doing a review now. Thanks for calling my attention to this.

**Comment by christopherporter1** [comment]
I don't have permission to close the issue.
