### ISSUE TITLE
Add guide in serverless section with function template example

### ISSUE THREAD

**Issue by jenglick** [Qiskit/documentation#2242]
### Describe the new content you are requesting.

A guide in the serverless section showing an example of building a function template using hamiltonian simulation and qiskit addons as context

cc @pandasa123 

### If this new content request is accepted, do you want to write the content?

I will write a draft of the proposed content

**Comment by garrison** [comment]
I expect to open a PR that closes this issue shortly, possibly as soon as tomorrow.

**Comment by beckykd** [comment]
From Jim: it will probably not be possible to get the function working until next year, and we won't publish it until then.  Installing the dependencies turns out to be much more difficult than we thought until new features are developed or until the whole thing (dependencies and all) is able to have a security review.

Closing for now
