### ISSUE TITLE
[ REFACTOR ] Split up install page into multiple pages

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#226]
The install page is getting quite long, I think it would be better to split this up into multiple pages under and "Install" sidebar heading in the Start section

In addition, the following information from qiskit.org doesn't have a home yet in onedocs, and I think an install section might be the best place for it.

- https://github.com/Qiskit/qiskit/blob/main/docs/configuration.rst
- https://qiskit.org/documentation/getting_started.html#platform-support

see related issues:
- https://github.com/Qiskit/documentation/issues/138
- https://github.com/Qiskit/documentation/issues/24

**Comment by abbycross** [comment]
Happy to help with this, @javabster. Are you thinking a set of pages like the following:

Install and set up Qiskit
Select an IBM Quantum channel (maybe this would contain both the IBM Quantum/Cloud platform channels setup)
Local configuration
Platform support (and can we put some adjective in front of "platform" to distinguish it from the IBM Quantum Platform? If so, what would be the right word?)

**Comment by abbycross** [comment]
As part of this work, we can look at https://github.ibm.com/IBM-Q-Software/iqp-channel-docs/pull/795/files to integrate the pieces of Jay's suggestions that would apply here.

**Comment by javabster** [comment]
yeah this is going to be a bit tricky, I'd recommend these pages:

- Install and Setup Qiskit (should include whats currently in the install and setup section, but also the platform support section)
- Select and Setup an IBM Quantum Channel (should include the select and setup sections for the ibm quantum channels)
- Qiskit local configuration

**Comment by javabster** [comment]
might need to reshuffle a bit but that feels right to start. And yes we should think of a different way to talk about "Platform support", discuss with @mtreinish on what would be appropriate

**Comment by mtreinish** [comment]
The platform support is a natural fit next to the install step because what you're local environment is dictates how you install :) But, it can be on a separate page if that fits better, we'd have to link to the platform support from the install guide. 

In general it's a pretty critical thing that we document, it's our contract with end users about where Qiskit is expected to work For projects like Qiskit that use a compiled language for part of the Python package, making it explicit the platforms we support upstream is necessary information for anyone installing qiskit. Otherwise if they do the normal `pip install qiskit` they'll get weird errors about a missing rust compiler or some random C++ library not being found because of an upstream dependency that is falling back to being built from source.
