### ISSUE TITLE
Don't refer to `/index` in API table of contents for Qiskit

### ISSUE THREAD

**Issue by SooluThomas** [Qiskit/documentation#227]
### URL to the relevant documentation

https://docs.quantum-computing.ibm.com/api/qiskit/index

### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] out-of-date content
- [X] broken link
- [ ] other

### Describe the fix.

When on the page https://docs.quantum-computing.ibm.com/api/qiskit and I try to click "qiskit" section under the API References (see screenshot), I am taken to the link https://docs.quantum-computing.ibm.com/api/qiskit/index and getting a 404. 

![image](https://github.com/Qiskit/documentation/assets/11485594/c5b2731e-0ff1-4ffa-831c-71b6e5e5af1b)

**Comment by Eric-Arellano** [comment]
The URL https://docs.quantum-computing.ibm.com/api/qiskit/index no longer breaks. Although it's still a little weird to refer to it with the `/index` since it should solely be `/api/qiskit`.

There's no longer a user bug, at least, though. So this can drop in priority.

The problem is here:

https://github.com/Qiskit/documentation/blob/5768b65983b2f9553759b4a3d58df2796ec7df05/docs/api/qiskit/_toc.json#L5-L8

Note that it's only a problem for Qiskit, not Runtime and Provider.
