### ISSUE TITLE
[ NEW PAGE ] Build/ Control flow with Qiskit

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#33]
## What the new page should cover:

```[tasklist]
### Tasks
- [ ] if statement
- [ ] for loop
- [ ] switch statement
- [ ] a warning box: dynamic=true,check out run section
```

## SME collaborators (involve for planning and review):
@jakelishman

**Comment by kevinsung** [comment]
I'm working to enable the for loop, switch statement, and while loop; see https://github.ibm.com/IBM-Q-Software/vt-qcf/issues/1419. As described in that issue, part of the task is to update the dynamic circuits documentation to demonstrate these new capabilities. Since this issue involves the same documentation, I think it would make sense to track that task in this issue to avoid duplicating effort. What do you all think?
