### ISSUE TITLE
When domain changes from quantum-computing.ibm.com to quantum.ibm.com, update docs

### ISSUE THREAD

**Issue by abbycross** [Qiskit/documentation#387]
When the domain name drops the "-computing", look for places in the docs where urls need updating. For example, links to learning pages will need to be updated.

**Comment by kkoci** [comment]
Hi

Sorry, when is it going to drop? By itself on production pages? Or will it be modified on documentation repo first? Just to have some context please?

I'd like to take on this as my first issue.

**Comment by Eric-Arellano** [comment]
Hey @kkoci, thanks for offering to help! 🙌 The change will be live once https://docs.quantum-computing.ibm.com redirects to https://docs.quantum.ibm.com some time next week. 

Feel free to open up a PR now that makes the change, and put `[DO NOT MERGE]` in the PR title. That way, we can start reviewing it and have everything ready.

If you haven't yet tried ripgrep (https://github.com/BurntSushi/ripgrep), it's a great way to search for what needs updating.

**Comment by kkoci** [comment]
Absolutely Awesome!

Just opened it, let me know if anything, whenever possible, it's half midnight here, so potentially, if there's something to check will do it in the morning 

Thanks a lot

PS = Will try ripgrep for sure, thanks for the input.

**Comment by Eric-Arellano** [comment]
Hey @kkoci, great work with https://github.com/Qiskit/documentation/pull/393! 

`quantum.ibm.com` went live today, so we're now good to go for you to open up a PR that switches over all URLs using `quantum-computing.ibm.com`. You'll want to make sure you start your branch from the latest `main` so that you incorporate your changes in 393. Would you be interested in this PR?

**Comment by Eric-Arellano** [comment]
Thanks @kkoci and @abbycross!
