### ISSUE TITLE
quantum_info "on this page" does not show methods properly

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/documentation#395]
### URL to the relevant documentation

If we look at the ["on this page" sidebar for `quantum_info` page](https://docs.quantum-computing.ibm.com/api/qiskit/quantum_info#references-1), I see `References` and `Examples`, instead of the actual methods like `hellinger_fidelity`

### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [x] other

### Describe the fix.

1. Go to https://docs.quantum-computing.ibm.com/api/qiskit/quantum_info#references-1
2. Try finding `hellinger_fidelity`
3. Look at the right side "on this page"

**Comment by woodsp-ibm** [comment]
I think this is likely the same problem described by this. I was just looking at QuantumCircuit docs https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.QuantumCircuit as I wanted to provide a link in an answer to compose. So I was looking in the right-hand sidebar for compose method and got confused when starting to look down the list under Methods that I come across an Examples heading at the same level. 

![image](https://github.com/Qiskit/documentation/assets/40241007/fcd4442f-5c72-40db-b735-83f20d5d61cd)


I realized after a bit that what was under it was still the methods though. Looking down the list there are other headings that seem to break up the list like `Notes` and `Example` These seem to be inline examples and notes for the methods, where the presentation in the sidebar makes it appear not the case.

I searched to see if the issue I was seeing was already noted. I think this is probably the same thing or at least related. The issue here describes the method being looked for as not found. In my case the method, compose, I was looking for was there it was just these "extra" headings that added confusion.

**Comment by Eric-Arellano** [comment]
This has now been fixed by @frankharkins in https://github.com/Qiskit/documentation/pull/683. The change is deployed for current docs and @arnaucasau will regenerate all the historical API docs with the change. Thank you, Frank, and thank you both for the feedback! 

`quantum_info`:

<img width="222" alt="Screenshot 2024-01-26 at 9 33 47 AM" src="https://github.com/Qiskit/documentation/assets/14852634/f825ec2b-51e8-4603-b24c-f19cfe237833">

`QuantumCircuit`:

<img width="231" alt="Screenshot 2024-01-26 at 9 34 35 AM" src="https://github.com/Qiskit/documentation/assets/14852634/6844edda-8650-4dfa-b3fb-883fefaea4f2">
