### ISSUE TITLE
[ REMOVE ] "Advanced Circuits" page

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#45]
This page will be replaced by a new "Circuit Contruction" page, see details here: https://github.com/Qiskit/documentation/issues/96

**Comment by abbycross** [comment]
@javabster Is this referring to the whole Advanced Circuit options section under Build? If so, we are already removing Conditional Reset as part of the October milestone, wondering if we should just remove the Pulse Gates page at the same time, rather than just have one straggler hanging out till the December milestone work begins.
