### ISSUE TITLE
[ REFACTOR ] Pulse pages

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#46]
The pulse pages (which came from Qiskit tutorials) are a bit old and possibly need a rewrite

What should be done:

- [x] remove https://github.com/Qiskit/documentation/blob/main/docs/build/__pulse_scheduler.ipynb
- [x] update the [existing pulse page](https://github.com/Qiskit/documentation/blob/main/docs/build/pulse.ipynb) to include a "next steps" CTA at the end, which should link out to https://qiskit.org/ecosystem/experiments/
- [ ] update the [existing pulse page](https://github.com/Qiskit/documentation/blob/main/docs/build/pulse.ipynb) to use the most up to date info (e.g. remove mentions of terra), check with Naoki what needs changing

### SME collaborators (involve for planning and review):
@nkanazawa1989

**Comment by nkanazawa1989** [comment]
I went over the current pulse tutorial. This looks covering almost all contents necessary to start pulse programming. Here are some advices to make it up to date; 

- [ ] Overall `Schedule` object is legacy and now user uses `ScheduleBlock` through the builder syntax. Note that schedule block format uses contextual scheduling approach for underlying instructions, which allows us to parameterize (i.e. taking `Parameter` object) instruction duration as well. In other words, instruction start time is undetermined until the time which it is executed. It's better to replace legacy `Schedule` with `ScheduleBlock`.

- [ ] This [paragraph](https://github.com/Qiskit/documentation/blob/b4ff7f01481897b1f6a9ef8aed2e4aab9a182b7c/docs/build/pulse.ipynb#L75-L79) is outdated. You can link to the [Qiskit Experiments tutorial](https://qiskit.org/ecosystem/experiments/tutorials/calibrations.html).

- [ ] To link a custom program to circuits, you can also add them to `Target` and transpile. There is a pass manager pass that implicitly extracts calibration data from the target and calls `add_calibration` for you. This might be convenient if you need to attach a calibration to multiple circuits, or need to manage multiple calibrations.

(example)
```python
from qiskit.providers.fake_provider import FakePerth
from qiskit.circuit import QuantumCircuit, Gate
from qiskit.pulse import builder, DriveChannel
from qiskit.compiler import transpile
from qiskit.transpiler import InstructionProperties

backend = FakePerth()

custom_gate = Gate("my_gate", 1, [])
qc = QuantumCircuit(1, 1)
qc.append(custom_gate, [0])
qc.measure(0, 0)

with builder.build() as custom_sched_q0:
    builder.play([0.1] * 160, DriveChannel(0))

backend.target.add_instruction(
    custom_gate, 
    {(0,): InstructionProperties(calibration=custom_sched_q0)},
)

qc = transpile(qc, backend)
```

- [ ] The [backend configuration](https://github.com/Qiskit/documentation/blob/b4ff7f01481897b1f6a9ef8aed2e4aab9a182b7c/docs/build/pulse.ipynb#L546) is not expected to be supported with backend V2 model (IBM backend supports them for backward compatibility). Instead, the [Target](https://qiskit.org/documentation/stubs/qiskit.transpiler.Target.html) object provides some scheduling constraints.

- [ ] Some pulse instructions are missing; [ShiftFrequency](https://qiskit.org/documentation/stubs/qiskit.pulse.instructions.ShiftFrequency.html#qiskit.pulse.instructions.ShiftFrequency) and [SetPhase](https://qiskit.org/documentation/stubs/qiskit.pulse.instructions.SetPhase.html#qiskit.pulse.instructions.SetPhase) are basic instructions that worth explaining. IBM backend doesn't support set phase, so it's also worth mentioning that supported instructions are backend dependent. 

- [ ] It would be helpful for users to have more detailed explanation for the shift/set frequency instruction. These instructions are not only changing the frequency of following pulses, but also changes the _frame of reference_ of the channel. Because a qubit oscillates at the frequency of its transition, the controller needs to sync with its oscillation otherwise unwanted Z drive is continuously applied. Usually the frame is matched with the frequency of the drive, and drive matches with the frequency of the transition; the Z drive is eliminated when the qubit frequency is calibrated properly. When you apply shift phase instruction, it changes the drive frequency and impacts the frame, in other words, it accumulates the phase (Z) as a function of shifted frequency and duration of the program. Specifically, when you shift the frequency by df and spend dt on that frame, the qubit may experience a phase rotation of df * dt. The programmer needs to take this into account to control their qubits precisely. We must also note that shift/set phase/frequency instruction is localized in pulse gate in IBM devices. This means accumulated phase and frequency shift are not carried over. Each pulse gate always starts from hardware default setting. This behavior is backend dependent (Qiskit is agnostic and doesn't enforce backend how to implement), and might be updated in the future controllers.

- [ ] Note that we are going to [refactor the pulse module](https://github.com/Qiskit/RFCs/blob/master/0012-Pulse-Compiler-and-IR.md). This won't be done before 1.0, but all `Channel` based representations are going to be deprecated. Currently there is no action needed.

- [ ] The [pulse library functions](https://github.com/Qiskit/documentation/blob/b4ff7f01481897b1f6a9ef8aed2e4aab9a182b7c/docs/build/pulse.ipynb#L639-L641) might be deprecated because there is not benefit of having them, i.e. the parametric instance can bootstrap waveform samples, when the backend doesn't support the parametric format. Please drop this paragraph (also use of the library in other cells).

- [ ] Some users are interested in changing the measurement pulse envelope. The [Kernel](https://github.com/Qiskit/documentation/blob/b4ff7f01481897b1f6a9ef8aed2e4aab9a182b7c/docs/build/pulse.ipynb#L784) is a subroutine that integrates time series of measurement response and generate an IQ data point, which must be classified into a quantum state by the discriminator. This indicates that if a user uses custom measurement stimulus, i.e. measurement pulse, one may need to update kernel setting not to deteriorate measurement SNR.

Lastly, I like the flow of explanation; pulse gate -> pulse instructions -> builder! Looking forward to seeing new documentation.

**Comment by abbycross** [comment]
Thank you so much @nkanazawa1989! I want to be sure I understand about replacing `Schedule` -- every time it is mentioned in the file, it should be replaced with `ScheduleBlock`, correct?

**Comment by abbycross** [comment]
Also @nkanazawa1989 -- where is the right spot in the file to add in your information on linking a custom program to circuits? And does it replace any other outdated information? thank you!

**Comment by abbycross** [comment]
> This [paragraph](https://github.com/Qiskit/documentation/blob/b4ff7f01481897b1f6a9ef8aed2e4aab9a182b7c/docs/build/pulse.ipynb#L75-L79) is outdated. You can link to the [Qiskit Experiments tutorial](https://qiskit.org/ecosystem/experiments/tutorials/calibrations.html).

I did this [here](https://github.com/Qiskit/documentation/pull/217/commits/93ab9e548cd250ba33410ed01fe9b25f36d28ed9)

**Comment by abbycross** [comment]
> The [backend configuration](https://github.com/Qiskit/documentation/blob/b4ff7f01481897b1f6a9ef8aed2e4aab9a182b7c/docs/build/pulse.ipynb#L546) is not expected to be supported with backend V2 model (IBM backend supports them for backward compatibility). Instead, the [Target](https://qiskit.org/documentation/stubs/qiskit.transpiler.Target.html) object provides some scheduling constraints.

I think I did this [here](https://github.com/Qiskit/documentation/pull/217/commits/48ab7444f7b4e412bf6ebe2ccf543a6f1b9ff373), does it look ok?

**Comment by abbycross** [comment]
> There are [more parametric pulses](https://github.com/Qiskit/documentation/blob/b4ff7f01481897b1f6a9ef8aed2e4aab9a182b7c/docs/build/pulse.ipynb#L570) supported by the library now, and this will be expanded in future. I recommend to just put a link to [the API doc](https://qiskit.org/documentation/apidoc/pulse.html#parametric-pulse-representation).

Done [here](https://github.com/Qiskit/documentation/pull/217/commits/5accacbb1c0f9a61f399c5df7b18e17855ed7d80)

**Comment by abbycross** [comment]
> The [pulse library functions](https://github.com/Qiskit/documentation/blob/b4ff7f01481897b1f6a9ef8aed2e4aab9a182b7c/docs/build/pulse.ipynb#L639-L641) might be deprecated because there is not benefit from having them, i.e. the parametric instance can bootstrap waveform samples, when the backend doesn't support the parametric format. Please drop this paragraph (also use of the library in other cells).

I [removed this paragraph](https://github.com/Qiskit/documentation/pull/217/commits/b1fa048145e715bde35fe941d6a6a876dcd9c971) but am not confident about identifying the library in other cells, so will need some assistance finishing this task.

**Comment by abbycross** [comment]
> Some users are interested in changing the measurement pulse envelope. The [Kernel](https://github.com/Qiskit/documentation/blob/b4ff7f01481897b1f6a9ef8aed2e4aab9a182b7c/docs/build/pulse.ipynb#L784) is a subroutine that integrates time series of measurement response and generates an IQ data point, which will be classified into a quantum state by the discriminator. This indicates that if a user uses custom measurement stimulus, i.e. measurement pulse, one may need to update kernel setting not to deteriorate measurement SNR.

I added this [here](https://github.com/Qiskit/documentation/pull/217/commits/57d9039710dd9bb3d8a39f695699be53f25f3c15).

**Comment by nkanazawa1989** [comment]
Sorry about slow response:

> I want to be sure I understand about replacing Schedule -- every time it is mentioned in the file, it should be replaced with ScheduleBlock, correct?

Yes, `ScheduleBlock` is preferred.

> where is the right spot in the file to add in your information on linking a custom program to circuits? And does it replace any other outdated information? thank you!

You can introduce this in the Custom gates section as a second approach.

 > I did this [here](https://github.com/Qiskit/documentation/pull/217/commits/93ab9e548cd250ba33410ed01fe9b25f36d28ed9); I still want to verify it is a 1:1 mapping, and whether the [instructions portion](https://docs.quantum-computing.ibm.com/build/pulse#schedule-instructions) is the same when you use ScheduleBlock instead of Schedule

Yes, instruction objects are common.

> I [removed this paragraph](https://github.com/Qiskit/documentation/pull/217/commits/b1fa048145e715bde35fe941d6a6a876dcd9c971) but am not confident about identifying the library in other cells, so will need some assistance finishing this task.

Please check https://github.com/Qiskit/qiskit/pull/11110

Thanks @abbycross for the great job :)
