### ISSUE TITLE
Documentation difficult to read (dark mode)

### ISSUE THREAD

**Issue by evmckinney9** [Qiskit/documentation#468]
### Feedback

Hello,

Regarding the new documentation pages, I have found that they can be somewhat difficult to read, especially in dark mode. My main issue is being able to quickly tell where one method starts and the next method begins.

[Example page](https://docs.quantum.ibm.com/api/qiskit/scheduler#circuit-scheduler):

![image](https://github.com/Qiskit/documentation/assets/47376937/58b2055a-2587-47f5-a2f3-a8c5cdf0b014)

I'm no design expert but I think the pages could use more headers or colors. 

[Slack thread](https://qiskit.slack.com/archives/GMT338B52/p1701442660737539)

### Other comments

1. The methods don't appear in the right sidebar
2. It's not clear what scope some lines are supposed to be under, e.g. in above "Pulse scheduling method" looks like it is under Return type but maybe also is a header for the next set of methods.
3. The black highlighting on dark gray backwards is too hard to see.
4. More variations of font sizes, separator lines, indentation, etc?

**Comment by javabster** [comment]
Thanks for this feedback! We are currently investigating ways to improve the layout of the API pages and hope to be able to start making improvements soon. We're aware this is a bad UI currently so we're prioritising this work highly

**Comment by Eric-Arellano** [comment]
1, 2, and 4 should now be addressed :) Please let us know if you have further suggestions to improve things!

@gracelindsell is going to look into 3 about the highlighting of inline code.

**Comment by gracelindsell** [comment]
@Eric-Arellano looks like the inline highlighting is currently set to Cool Gray 100, RGB 18,22,25. we should change that to Accessibility/Black, RGB 0,0,0. this will help create more of an inverse highlight.

**Comment by Eric-Arellano** [comment]
Thanks again, @evmckinney9, for the feedback! We've rolled out a few improvements since you opened this:

- inline code now has a border around it on dark mode, which improves contrast
- code blocks have larger font
- code blocks comments use a different color for better contrast
- the API docs were overall redesigned to use colored bars to better show where distinct methods/functions/classes/attributes are

We have two more planned improvements for API docs:

* https://github.com/Qiskit/documentation/issues/1361
* https://github.com/Qiskit/documentation/issues/1395

Please let us know if you have any other feedback or suggestions on how to make the docs more useful. Your feedback was extremely useful and prompted the first chaneg of adding a border to inline code on dark mode.


<img width="811" alt="Screenshot 2024-08-08 at 10 51 30 AM" src="https://github.com/user-attachments/assets/1888670b-9466-4bcb-9f7d-7ed2b06696e2">

<img width="610" alt="Screenshot 2024-08-08 at 10 51 46 AM" src="https://github.com/user-attachments/assets/574ecab3-d8cf-4905-a23e-9511882a207c">

<img width="737" alt="Screenshot 2024-08-08 at 10 52 22 AM" src="https://github.com/user-attachments/assets/b0c9d685-22c3-44a4-84b3-bc15586f6d87">
