### ISSUE TITLE
Broken link for Runtime method moving to its class page

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/documentation#533]
Googling "qiskit faulty qubits", the first result takes me to the non-existing page https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.IBMBackend.check_faulty.

**Comment by Eric-Arellano** [comment]
Thank you! The redirect should be going to https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.IBMBackend#check_faulty. A couple months ago, we had dedicated HTML pages for each method but methods are now documented on their class page.

I have a PR up to improve our redirect logic so that this is handled automatically. Thanks for the report! It was very helpful :)

**Comment by Eric-Arellano** [comment]
This is now fixed. Note that the URL https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.IBMBackend.check_faulty still 404s and always will. But, the Google result https://qiskit.org/ecosystem/ibm-runtime/stubs/qiskit_ibm_runtime.IBMBackend.check_faulty.html now takes you correctly to https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.IBMBackend#check_faulty.

Thanks again for the report!
