### ISSUE TITLE
External link checker should create a GitHub issue with errors

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#547]
I didn't realize that we've had broken links for a couple of days. That's because right now you have to manually check https://github.com/Qiskit/documentation/actions/workflows/external-link-checker.yml.

<img width="1157" alt="Screenshot 2023-12-21 at 2 43 49 PM" src="https://github.com/Qiskit/documentation/assets/14852634/186f3b5f-f7cf-4173-a9b4-8d43dc4b9868">

It'd be neat if instead the action would create a GitHub issue with any problems. Ideally, it would update the existing issue rather than creating a new issue every day.

**Comment by Eric-Arellano** [comment]
@arnaucasau @frankharkins can I get your thoughts on what you think is desirable? The question is how to handle multiple days in a row of failures. If Monday was broken and we already opened an issue, what do we do on Tuesday if it's not yet fixed?

1. Create a new issue?
2. Update an existing issue?

I believe that updating an existing issue is harder than it sounds - we need to preserve state across runs of what the latest issue was. The only viable/simple alternative for 2 I can think of us is to hardcode a specific issue number. Our action will make sure that issue is open and either add a comment or edit the issue description. Because it reopens the issue if closed, it's fine for people to close the issue whenever it's fixed.

What do you think? If you like my plan for updating an existing issue, do you think it's better to rewrite the PR description or add a new comment? The new comment will trigger a new GitHub notification, whereas editing is silent.

**Comment by arnaucasau** [comment]
I like your plan of updating an existing issue rather than creating a new one every day. I think we can have one fixed issue that through GitHub actions will be re-opened when necessary to edit the description. In my opinion, editing is better than creating a new comment to avoid having multiple notifications for the same links, but we can still add a new comment if we want only when we have a new broken link, and not when the broken links are the same as the day before. Something like:

```bash
Link checker searches for broken links

if found and the issue is closed:
    Re-open the issue 

Update the description with the broken links

if new broken links
    Post a comment to inform about the new broken links
```

The last step can be done by comparing the output of the link checker and the issue description. To avoid having multiple comments informing about the new broken links, maybe we can delete the previous one (if existed) and create a new comment to trigger the notifications.

However, having one issue with the description updated with all the broken links and not having more notifications than the first one (re-open the issue), I think is possibly enough. What do you think?

Some information I found about the GitHub actions:
1. https://github.com/peter-evans/create-or-update-comment
2. https://github.com/peter-evans/find-comment

**Comment by Eric-Arellano** [comment]
> However, having one issue with the description updated with all the broken links and not having more notifications than the first one (re-open the issue), I think is possibly enough. What do you think?

Thanks for thinking this all through! Let's go with simply editing the top-level comment for now. I want to keep this logic simple given how much complexity the repo already has. If it is not working well, then we can make this more robust.

> Some information I found about the GitHub actions:

Thanks! Rather than using a third-party action, I plan to use the `gh` CLI directly. Apparently it is now installed in GitHub Actions. I prefer us using first-party over third-party, including to reduce supply chain security risk.

**Comment by Eric-Arellano** [comment]
This issue becomes a little less important thanks to https://github.com/Qiskit/documentation/pull/592. We'll now have two additional places that we're notified of failures.
