### ISSUE TITLE
Image issues in transpiler stages topic

### ISSUE THREAD

**Issue by beckykd** [Qiskit/documentation#657]
### URL to the relevant documentation

https://docs.quantum.ibm.com/transpile/transpiler-stages

### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [X] other

### Describe the fix.

There are a couple of issues with images on this page.  

- [ ] The first image is in dark mode.
- [ ] transpiler-11 is in there twice.  I'm pretty sure the one after "The transpilation output varies due to the stochastic SWAP mapper. Therefore, the numbers below will likely change each time you run the code." is supposed to be a different image.

**Comment by beckykd** [comment]
@abbycross or @kaelynj Can one of you help me figure this out?

**Comment by abbycross** [comment]
I suspect that the duplicate image Becky mentions above (see screenshot) can be removed altogether, unless @kaelynj do you recall if an image is intentional in this spot?
<img width="671" alt="Screenshot 2024-01-19 at 3 43 40 PM" src="https://github.com/Qiskit/documentation/assets/28769477/52851020-d9ce-4e14-9e2b-ff71bbf11425">

**Comment by kaelynj** [comment]
I used the same image for these two examples since they prepare the same example state.  Though I see the point about having the same image twice.  In the first part where it talks about the routing stage it might be better to instead add in a graph image of the hardware qubits that were assigned after the `trivial_layout` method was selected using `plot_circuit_layout()` from the `qiskit.visualization` module.

**Comment by abbycross** [comment]
I tried it out, using example lines of code from the API, and got this -- @kaelynj does this look like what you'd expect?
﻿﻿
<img width="410" alt="Screenshot 2024-01-22 at 12 45 03 PM" src="https://github.com/Qiskit/documentation/assets/28769477/3c7fe7fa-d09b-4246-ab8f-7e2b89f5fc24">

This is the code I added to the cell
```
new_circ_lv1 = transpile(ghz, backend=backend, optimization_level=1)
plot_circuit_layout(new_circ_lv1, backend)
```

**Comment by kaelynj** [comment]
Yep!  This shows the point that section is making about the need to select hardware qubits in a smarter way.  The text might need to change a bit to reflect the different figure.  Do you want/need me to make those changes?

**Comment by beckykd** [comment]
Thanks @kaelynj and @abbycross !

**Comment by beckykd** [comment]
> I used the same image for these two examples since they prepare the same example state. Though I see the point about having the same image twice. In the first part where it talks about the routing stage it might be better to instead add in a graph image of the hardware qubits that were assigned after the `trivial_layout` method was selected using `plot_circuit_layout()` from the `qiskit.visualization` module.

If it's not a mistake, it's fine with me.  I just wanted to make sure :)
