### ISSUE TITLE
Search index should adapt to selected API version and language translation

### ISSUE THREAD

**Issue by kielpins-qctrl** [Qiskit/documentation#859]
### Feedback

I am using Qiskit v0.46. When using the docs page, the choice of v0.46.0 on the sidebar reverts to v1.0 whenever I click on any result from the Search tool. Therefore, I can't search on any v0.46.0 docs as I just get the v1.0 version.

**Comment by kielpins-qctrl** [comment]
Can I ask for an update on this issue? The docs are now entirely unusable for older versions of Qiskit.

**Comment by Eric-Arellano** [comment]
Hey @kielpins-qctrl, thank you for taking the time to make this suggestion! That's helpful.

We finished figuring out today the design for this. We don't want the search index to have all historical API versions in the same loaded index: if we did that, you would get a ton of duplicate results but over different API pages. Instead, the plan is to have search be for the current API version you've selected:

- E.g. if you're on Qiskit 0.46 docs, search will use Qiskit 0.46
- Otherwise, e.g. if you're not on API docs, we'll use the latest released version, like Qiskit 1.0

(We were also figuring out the right way to update the search index for historical versions without blowing up our CI build time.)

I'll begin implementation this afternoon and hope to have this up by the end of next week.

**Comment by Eric-Arellano** [comment]
Update: still in progress and I'm about 85% there. A couple unrelated things got in the way last week. Landing this is my top priority.

**Comment by Eric-Arellano** [comment]
Update that this got blocked by concern that the UX would be too confusing without a frontend explaining what is going on: https://github.com/Qiskit/documentation/issues/1080. We agreed to a design for https://github.com/Qiskit/documentation/issues/1080 today and I'm making progress on implementing it. Pardon the delay!

**Comment by kielpins-qctrl** [comment]
Thanks for the update. I'm a bit surprised at the concern... this is a common pattern as seen in e.g. NumPy and Pandas docs.

**Comment by Eric-Arellano** [comment]
The biggest concern is how the search is for several distinct APIs: Qiskit SDK, Qiskit Runtime client, Qiskit Runtime REST API, and Qiskit Provider. The semantics are nuanced that you are only changing the version of the current project you're looking at, and we still use the latest API versions for all the other projects. 

Here's how we'll render the API search in general:

![image](https://github.com/Qiskit/documentation/assets/14852634/160a1ba4-3f7a-49d6-a15c-9dd10ea30340)

When you're on a historical or dev version of a specific project:

![image](https://github.com/Qiskit/documentation/assets/14852634/275e5688-fac0-4dd9-b295-56bf128374a5)

Docs and Learning don't have any description:

![image](https://github.com/Qiskit/documentation/assets/14852634/ff9961d7-8cc5-4643-b2d0-fea388ab6965)

**Comment by Eric-Arellano** [comment]
Now live! E.g. search box on https://docs.quantum.ibm.com/api/qiskit/0.46

<img width="597" alt="Screenshot 2024-04-15 at 12 15 18 PM" src="https://github.com/Qiskit/documentation/assets/14852634/1471b132-bbb9-422e-94ed-c2b5476cbae8">

Pardon that this took longer than expected. There were a couple of unexpected delays like a code freeze due to an issue with Cloudflare caching that we recently figured out.

Thank you @kielpins-qctrl for this suggestion! Please continue to share suggestions about how to improve the docs :)
