### ISSUE TITLE
Update documentation regarding primitives and ISA circuits

### ISSUE THREAD

**Issue by beckykd** [Qiskit/documentation#880]
From Slack

Some questions on primitives moving to ISA-only circuits

It sounds like the immediate plan is to advise users to do the observable manipulation locally. For SparsePauliOp, apply_layout makes this easy. But there isn't a built-in equivalent for the other ObservableLike types (str, Pauli, or dict). Is there a way to cover these other cases?   Need documentation on how users should handle the other cases themselves.

Possible SME @jakelishman

**Comment by javabster** [comment]
since qiskit 1.1 Pauli now has apply_layout, and generally speaking we always recommend using SparsePauliOp in our docs. I think we should focus on encouraging people to use SparsePauliOp as the "best" way to do things, and if we come to a point where we have to document these other types then we can reopen this issue
