### ISSUE TITLE
Move Migration Guides to API ref dropdown

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#90]
The migration guides currently live in the "Start" section but it was decided that it would be better to add it as a section under the API reference dropdown. At this point we should also reconsider which migration guides we keep, and which are no longer needed and can be removed

### Needs further discussion:

we currently have the following migration guides:
- https://docs.quantum-computing.ibm.com/start/compare
- https://docs.quantum-computing.ibm.com/start/migrate
- https://docs.quantum-computing.ibm.com/start/migrate-examples
- https://qiskit.org/documentation/migration_guides/algorithms_migration.html (to be migrated to onedocs soon)
- https://qiskit.org/documentation/migration_guides/opflow_migration.html  (to be migrated to onedocs soon)
- https://qiskit.org/documentation/migration_guides/qi_migration.html  (to be migrated to onedocs soon)

We should definitely keep the algos, opflow and quantum instance migration guides, but there is some debate over which (if any) of the 3 runtime migration guides we should keep. @lerongil @jyu00 @ElePT @blakejohnson please feel free to weigh in so we can come to an agreement on this

**Comment by ElePT** [comment]
I don't know what are the current arguments for/against keeping the runtime migration guides, so I might be repeating arguments, but here are a few thoughts on my side:

1. A lot of the content of these guides is somewhere between a migration guide and a how-to (except for [the provider guide](https://docs.quantum-computing.ibm.com/start/migrate#migrate-setup-from-qiskit-ibmq-provider), which is more of a typical migration guide), and I think that it does necessarily have to live in a "migration guides" section. On top of that,  https://docs.quantum-computing.ibm.com/start/compare is more of an informative note than a guide per se. I could see it being merged with other docs page or kept as kind of general/introductory content (should also be checked to make sure that the narrative around backend.run and the primitives is coherent).
2. I admit that the migration examples in https://docs.quantum-computing.ibm.com/start/migrate-examples are fairly convoluted. This was because the point we were migrating "from" was not very clear, I tried to cover as many paths as possible, and honestly, I am not too satisfied with them. I can also see that my "from" was an algorithms/applications dev perspective (referring to opflow/quantum instance), which is no longer part of the qiskit narrative, and can contribute to the confusion.
3. Despite what I said in 2, there are important points conveyed by https://docs.quantum-computing.ibm.com/start/migrate-examples that I think are **key** to cover somewhere in the documentation, be it as a migration guide or somewhere else, those are: **a clear explanation of what the different primitives are useful for, how to import the right primitive for your task, and how to change from one primitive to the other.** 

For this reason, I don't think that simply deleting these guides is a good idea. I think that this content (content that shows the context around Aer primitives, runtime primitives, backend primitives...) needs to live somewhere, and somewhere easy to find, because it is really one of the most commonly asked questions by external users. I understand that, in particular, Aer primitives could be tricky to explain, as they are kind of "external", but at least a clear separation between terra (reference/backend) and runtime ones must be made. People go to the runtime tutorials where most of the example use reference primitives, and they get extremely confused with sessions and what does what. I think if would be extremely helpful to have this compiled in a documentation page that we could easily share with our users when asking about it. So far, the closest thing I am aware we have are these migration examples.
